### ISSUE TITLE
is mecca no longer used?

### ISSUE THREAD

**Issue by SingingBush** [dlang-community/mecca#29]
I cloned the project and found that it won't compile with dmd 2.105.0 so decided to try building with a wide range of dmd releases:

| DMD version | outcome |
| :-- | :-- |
| 2.105.2 (dmd-latest) | dub build fails `src/mecca/containers/pools.d(76,21): Error: `Elem[512]` size 18446744073709551615 * 512 exceeds 0x7fffffff size limit for static array` |
| 2.100.2 | dub build fails `src/mecca/lib/memory.d(465,32): Error: function `mecca.lib.memory.DRuntimeStackDescriptor._slock` conflicts with variable `mecca.lib.memory.DRuntimeStackDescriptor._slock` at src/mecca/lib/memory.d(464,54)` |
| 2.095.1 | dub build fails `src/mecca/lib/memory.d(464,54)` |
| 2.090.1 | dub build fails `src/mecca/lib/memory.d(464,54)` |
| 2.078.3 | `src/mecca/platform/os/linux/time.d(75): Assertion failure: hangDetectorTimerId is null` |
| 2.076.1 | `src/mecca/platform/os/linux/time.d(75): Assertion failure: hangDetectorTimerId is null` |

is this project no longer maintained/used?

**Comment by jacob-carlborg** [comment]
No, unfortunately it's not maintained. Weka stopped maintaining it so it was moved to dlang-community in the hope it would get maintained there, but unfortunately not.
